/*!
 * \file      sx1276-board.h
 *
 * \brief     Target board SX1276 driver implementation
 *
 * \author    ck ( beelinker )
 */
 
#ifndef __SX1276_BOARD_H__
#define __SX1276_BOARD_H__

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>
#include "nrf_drv_gpiote.h"
#include "sx1276.h"

/*!
 * \brief Radio hardware registers initialization definition
 *
 * \remark Can be automatically generated by the SX1276 GUI (not yet implemented)
 */
#define RADIO_INIT_REGISTERS_VALUE                \
{                                                 \
    { MODEM_FSK , REG_LNA                , 0x23 },\
    { MODEM_FSK , REG_RXCONFIG           , 0x1E },\
    { MODEM_FSK , REG_RSSICONFIG         , 0xD2 },\
    { MODEM_FSK , REG_AFCFEI             , 0x01 },\
    { MODEM_FSK , REG_PREAMBLEDETECT     , 0xAA },\
    { MODEM_FSK , REG_OSC                , 0x07 },\
    { MODEM_FSK , REG_SYNCCONFIG         , 0x12 },\
    { MODEM_FSK , REG_SYNCVALUE1         , 0xC1 },\
    { MODEM_FSK , REG_SYNCVALUE2         , 0x94 },\
    { MODEM_FSK , REG_SYNCVALUE3         , 0xC1 },\
    { MODEM_FSK , REG_PACKETCONFIG1      , 0xD8 },\
    /* FIFO threshold set to 32 (31+1) */         \
    { MODEM_FSK , REG_FIFOTHRESH         , 0x9F },\
    { MODEM_FSK , REG_IMAGECAL           , 0x02 },\
    { MODEM_FSK , REG_DIOMAPPING1        , 0x00 },\
    { MODEM_FSK , REG_DIOMAPPING2        , 0x30 },\
    { MODEM_LORA, REG_LR_PAYLOADMAXLENGTH, 0x40 },\
}                                                 \

#define RF_MID_BAND_THRESH                  525000000

#define SPI_INSTANCE                        0
#define SPI_TRANSFER_BUF_LEN                64
#define REGVERSION_DEFAULT                  0x12

void sx1276_status_io_init(nrfx_gpiote_evt_handler_t st_callback);
void sx1276_reset(void);
uint32_t sx1276_get_dio0pin_state(void);
bool sx1276_check_rf_frequency( uint32_t frequency );
uint32_t sx1276_get_board_tcxo_wakeup_time( void );
void radio_spi_init(void);
ret_code_t radio_spi_transfer(uint8_t *tx_buf, uint8_t tx_buf_len,
                              uint8_t *rx_buf, uint8_t rx_buf_len) ;
void sx1276_io_lowpower_manage(void);

#ifdef __cplusplus
}
#endif

#endif // __SX1276_BOARD_H__
